-- Migration: Add photos table for object images
-- Generated by M011 S01

BEGIN;

-- Create photos table
CREATE TABLE "photos" (
    "id" TEXT NOT NULL,
    "objectId" TEXT NOT NULL,
    "url" TEXT NOT NULL,
    "position" INTEGER NOT NULL DEFAULT 0,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "photos_pkey" PRIMARY KEY ("id")
);

-- Add index on objectId
CREATE INDEX "photos_objectId_idx" ON "photos"("objectId");

-- Add composite index for ordering
CREATE INDEX "photos_objectId_position_idx" ON "photos"("objectId", "position");

-- Add foreign key to objects table
ALTER TABLE "photos" ADD CONSTRAINT "photos_objectId_fkey"
    FOREIGN KEY ("objectId") REFERENCES "objects"("id") ON DELETE CASCADE ON UPDATE CASCADE;

COMMIT;
